### PR TITLE
An adaptation of django-example to django 1.7.x

### PR DESCRIPTION
**Pull request by ZackYovel**
* removed the old project and installed a new one (dj-1.7.7)
* moved openshiftlibs.py to top folder (to make fresh django installations smoother)
* added GETTING-STARTED comments where values are expected to be changed by the user

### CODE REVIEW

**Comment by ZackYovel** [comment]
Hi, I've been looking for a way to deploy a django app to openshift, and this project worked for me after some adaptations. Here are the fruites of my labor, hopefully others can enjoy them as well.
I intend to create two main branches (for now) one is this master, with a up-to-date django app,
and the second will be app-less, to be used as a wrapper/adapter into which new django installations
could be made or even existing apps from other platforms could be copy-pasted for an easy deploy.

**Comment by bparees** [comment]
1) please squash these commits
2) I tried to run your repo (master) and hit issues, the steps i followed were:

rhc app create django python-2.6
cd django
git remote add upstream -m master git://github.com/ZackYovel/django-example.git
git pull -s recursive -X theirs upstream master
git push

can you confirm this is in a working state?

**Comment by ZackYovel** [comment]
Squashed.

django 1.7.x requires python 2.7: https://docs.djangoproject.com/fr/1.7/releases/1.7/#python-compatibility

I followed your steps (except I used python-2.7) after squashing and successfully deployed an app.

**Comment by bparees** [comment]
got it.  Works now.  can you update the readme instructions so they indicate to use 2.7 instead of 2.6?

**Comment by ZackYovel** [comment]
Fixed, Thanks for pointing this out.

**Comment by mfojtik** [comment]
LGTM @soltysh any last words? ;-)

**Comment by soltysh** [comment]
LGTM as well

**Comment by mfojtik** [comment]
@ZackYovel thanks for doing this

**Comment by ZackYovel** [comment]
You are wellcome, thanks for the original work :)

**Comment by bparees** [comment]
@ZackYovel thanks!

**Pull request merged**
